Homework 3-4
vkirilenko/devops-data pull request #2
Opened 2021-12-04 08:34 UTC by vkirilenko

@tsukabris Comment plz!

2021-12-13 19:05 UTC, Tsukabris commented on hw3-4/README.md
> +   _Command:_ __man awk | sed -n '1370,1381p' > extract.txt__
А что будет, если искомые строки будут в другом месте?

2021-12-13 19:06 UTC, Tsukabris commented on hw3-4/README.md
> +  ![1.1](img/1.1.png)
В следующий раз лучше вставлять код сюда, читать с жпегов очень не комильфо

2021-12-13 19:09 UTC, Tsukabris requested changes
Выложи код и результат выполнения в текстовом виде, скриншоты это не самый рациональный вариант

2021-12-13 20:08 UTC, vkirilenko commented on hw3-4/README.md
> +  ![1.1](img/1.1.png)
Вставлять что именно? Весь вывод терминала?
Именно сам код есть в md файле, в строчке Command

2021-12-13 20:09 UTC, vkirilenko commented on hw3-4/README.md
> +   _Command:_ __man awk | sed -n '1370,1381p' > extract.txt__
Очевидно будут сохранены другие строки.
Имеете в виду, что задание было направлено не на сохранение текста в файл, а на паттерн поиска определенных строк?

2021-12-14 09:26 UTC, vkirilenko commented
> Выложи код и результат выполнения в текстовом виде, скриншоты это не самый рациональный вариант

Переделал первую задачу.
Заменил скриншоты на текст.

2021-12-14 11:44 UTC, Tsukabris approved these changes
Принято

2021-12-14 12:17 UTC, merged