Homework 17-18
vkirilenko/devops-data pull request #9
Opened 2021-12-26 16:39 UTC by vkirilenko

@cakemanator Comment, plz!

2021-12-26 17:58 UTC, Cakemanator requested changes

2021-12-26 17:58 UTC, Cakemanator commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Можно сделать запрос еще более "узким", только порта и адреса маловато

2021-12-26 19:24 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Теоретически этих двух флагов должно хватать. Единственное, что еще можно добавить, это только -A для захвата ASCII данных. Я только не уверен, будет ли tcpdump с этим флагом захватывать только ASCII или выводить ASCII из полного захваченного пакета. Вывод то будет одинаковый в обоих случаях.

2021-12-26 19:25 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Наверное, можно еще использовать флаг tcp, но это уже оверкилл, как мне кажется. И так есть порт для HTTP.

2021-12-29 09:37 UTC, Cakemanator commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
tcp это не только http, да и порт 80 не обязательно (хоть и наиболее часто) слушается протоколом http.
Плюс, указано чтобы команда была настолько "узкой", насколько возможно

2021-12-29 13:30 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Я не понимаю тогда насколько "узкой" должна быть команда. Любой порт, любой протокол, но только конкретный адрес? Так это наоборот расширит захват.

2021-12-29 13:31 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Если делаю 
```sudo tcpdump -A -q -t -i enp0s3 'dst google.com and port 80' -w google.pcap```
то получаю тот же вывод:
```
vladimir@localhost:~$ tcpdump -A -r google.pcap
reading from file google2.pcap, link-type EN10MB (Ethernet)
00:30:15.782205 IP localhost.localdomain.51842 > lu-in-f139.1e100.net.http: Flags [S], seq 1126766193, win 29200, options [mss 1460,sackOK,TS val 15411481 ecr 0,nop,wscale 7], length 0
E..<?h@.@.!=
...J}.....PC).q......r..E.........
..).........
00:30:15.789783 IP localhost.localdomain.51842 > lu-in-f139.1e100.net.http: Flags [.], ack 65088002, win 29200, length 0
E..(?i@.@.!P
...J}.....PC).r..*.P.r..1..
00:30:15.790027 IP localhost.localdomain.51842 > lu-in-f139.1e100.net.http: Flags [P.], seq 0:74, ack 1, win 29200, length 74: HTTP: GET / HTTP/1.1
E..r?j@.@.!.
...J}.....PC).r..*.P.r..{..GET / HTTP/1.1
User-Agent: curl/7.29.0
Host: google.com
Accept: */*


00:30:15.807030 IP localhost.localdomain.51842 > lu-in-f139.1e100.net.http: Flags [.], ack 529, win 30016, length 0
E..(?k@.@.!N
...J}.....PC)....,.P.u@.1..
00:30:15.810334 IP localhost.localdomain.51842 > lu-in-f139.1e100.net.http: Flags [F.], seq 74, ack 529, win 30016, length 0
E..(?l@.@.!M
...J}.....PC)....,.P.u@.1..
00:30:15.818491 IP localhost.localdomain.51842 > lu-in-f139.1e100.net.http: Flags [.], ack 530, win 30016, length 0
E..(u{@.@..=
...J}.....PC)....,.P.u@....
```

2021-12-29 13:33 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Проще остановиться на варианте **sudo tcpdump 'tcp port 80 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)'** да и все.

2021-12-29 14:48 UTC, Cakemanator commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
В твоем случае достаточно было бы просто еще протокол обозначить)
Суть самого задания в том, чтобы обозначить как можно больше параметров в команде (конкретный хост, конкретный порт, конкретный протокол), можно даже конкретные типы запросов отлавливать (GET, POST, HTTP, etc).

2021-12-29 19:07 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
О как... Но если еще сузить, то ```sudo tcpdump -A -q -t -i enp0s3 'dst google.com and port 80 and tcp' -w google3.pcap``` вообще не ловит тело запроса. 
```
vladimir@localhost:~$ sudo tcpdump -A -q -t -i enp0s3 'dst google.com and port 8          0 and tcp' -w google3.pca
tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), capture size 262144 b          ytes
^C0 packets captured
4 packets received by filter
0 packets dropped by kernel
vladimir@localhost:~$ tcpdump -A -r google3.pcap
reading from file google3.pca, link-type EN10MB (Ethernet)
```
В чем смысл такого сужения?

2021-12-29 19:09 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
А, затупил. Надо было http, да?
Тогда все равно разницы нет.
```
vladimir@localhost:~$ sudo tcpdump -A -q -t -i enp0s3 'dst google.com and port 80 and http' -w google3.pcap
tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), capture size 262144 bytes
^C6 packets captured
10 packets received by filter
0 packets dropped by kernel
vladimir@localhost:~$ tcpdump -A -r google3.pcap                                          reading from file google3.pcap, link-type EN10MB (Ethernet)
01:26:55.955715 IP localhost.localdomain.33130 > le-in-f139.1e100.net.http: Flags [S], seq 99122235, win 29200, options [mss 1460,sackOK,TS val 18811654 ecr 0,nop,wscale 7], length 0
E..<w=@.@..g
...J}...j.P..|;......r.$F.........
............
01:26:55.975217 IP localhost.localdomain.33130 > le-in-f139.1e100.net.http: Flags [.], ack 24064002, win 29200, length 0
E..(w>@.@..z
...J}...j.P..|<.o0.P.r.$2..
01:26:55.975419 IP localhost.localdomain.33130 > le-in-f139.1e100.net.http: Flags [P.], seq 0:74, ack 1, win 29200, length 74: HTTP: GET / HTTP/1.1
E..rw?@.@../
...J}...j.P..|<.o0.P.r.$|..GET / HTTP/1.1
User-Agent: curl/7.29.0
Host: google.com
Accept: */*


01:26:56.310759 IP localhost.localdomain.33130 > le-in-f139.1e100.net.http: Flags [.], ack 529, win 30016, length 0
E..(w@@.@..x
...J}...j.P..|..o2.P.u@$2..
01:26:56.318243 IP localhost.localdomain.33130 > le-in-f139.1e100.net.http: Flags [F.], seq 74, ack 529, win 30016, length 0
E..(wA@.@..w
...J}...j.P..|..o2.P.u@$2..
01:26:56.330170 IP localhost.localdomain.33130 > le-in-f139.1e100.net.http: Flags [.], ack 530, win 30016, length 0
E..(.=@.@..{
...J}...j.P..|..o2.P.u@....
```

2021-12-30 13:47 UTC, Cakemanator commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Да, разницы нет, но здесь суть в том, чтобы получить наиболее "узкую" команду.
Это сейчас мы слушаем обычные http запросы (которые сами же и шлем), иногда приходится слушать целый интерфейс и отлавливать только конкретные протоколы с конкретными параметрами (например общение кубернетовских нод). Задание было дано для понимания, что мы можем ловить весь траффик, а потом чем-нибудь его сортировать (тратя огроное кол-во времени), а можем сразу задать нужные параметры и получить более-менее нужные пакеты данных.

2021-12-30 13:48 UTC, Cakemanator approved these changes

2021-12-30 15:00 UTC, vkirilenko commented on hw17-18/README.md
> +vladimir@localhost:~$ sudo tcpdump -i enp0s3 dst google.com and port 80 -w google.pcap
Понял, спасибо за объяснение! Так то это логично, конечно. Я бы даже сказал, что такое объяснение надо бы прямо в лекцию добавить. :)

2021-12-30 15:01 UTC, merged